function out1 = iiwa_FK_symbolic_T45(th4)
%IIWA_FK_SYMBOLIC_T45
%    OUT1 = IIWA_FK_SYMBOLIC_T45(TH4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    24-Jul-2018 11:29:55

t2 = sin(th4);
t3 = cos(th4);
out1 = reshape([t3,0.0,t2,0.0,-t2,0.0,t3,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,1.9e1./1.0e2,1.0],[4,4]);
