function out1 = iiwa_FK_symbolic_T23(th2)
%IIWA_FK_SYMBOLIC_T23
%    OUT1 = IIWA_FK_SYMBOLIC_T23(TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    24-Jul-2018 11:29:54

t2 = sin(th2);
t3 = cos(th2);
out1 = reshape([-t3,0.0,t2,0.0,t2,0.0,t3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.9e1./1.0e2,1.0],[4,4]);
